#
# Created by gmakemake (Ubuntu Jul 25 2014) on Sun Nov 20 23:50:31 2022
#

#
# Definitions
#

.SUFFIXES:
.SUFFIXES:	.a .o .c .C .cpp .s .S
.c.o:
		$(COMPILE.c) $<
.C.o:
		$(COMPILE.cc) $<
.cpp.o:
		$(COMPILE.cc) $<
.S.s:
		$(CPP) -o $*.s $<
.s.o:
		$(COMPILE.cc) $<
.c.a:
		$(COMPILE.c) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%
.C.a:
		$(COMPILE.cc) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%
.cpp.a:
		$(COMPILE.cc) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%

CC =		gcc
CXX =		g++

RM = rm -f
AR = ar
LINK.c = $(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
LINK.cc = $(CXX) $(CXXFLAGS) $(CPPFLAGS) $(LDFLAGS)
COMPILE.c = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc = $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c
CPP = $(CPP) $(CPPFLAGS)
########## Flags from header.mak


CFLAGS = -std=c99 -ggdb -Wall -Wextra
# -pedantic complains about assignments to pointer to functions


########## End of flags from header.mak


CPP_FILES =	
C_FILES =	place_ip.c trie.c true.c
PS_FILES =	
S_FILES =	
H_FILES =	trie.h
SOURCEFILES =	$(H_FILES) $(CPP_FILES) $(C_FILES) $(S_FILES)
.PRECIOUS:	$(SOURCEFILES)
OBJFILES =	trie.o true.o 

#
# Main targets
#

all:	place_ip 

place_ip:	place_ip.o $(OBJFILES)
	$(CC) $(CFLAGS) -o place_ip place_ip.o $(OBJFILES) $(CLIBFLAGS)

#
# Dependencies
#

place_ip.o:	trie.c trie.h
trie.o:	trie.h
true.o:	

#
# Housekeeping
#

Archive:	archive.tgz

archive.tgz:	$(SOURCEFILES) Makefile
	tar cf - $(SOURCEFILES) Makefile | gzip > archive.tgz

clean:
	-/bin/rm -f $(OBJFILES) place_ip.o core

realclean:        clean
	-/bin/rm -f place_ip 
